services:
  # Nginx front-facing server
  nginx:
    image: nginx:1.25
    container_name: wp_dev_nginx
    restart: unless-stopped
    ports:
      - "8080:80" # browse site at http://localhost:8080
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./wp-content:/var/www/html/wp-content:delegated
      - ./docker/wordpress/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./uploads.ini:/etc/nginx/uploads.ini
    depends_on:
      - wordpress
    networks:
      - wp-network
    env_file:
      - .env

  # WordPress (PHP-FPM)
  wordpress:
    build:
      context: ./docker/wordpress
      dockerfile: Dockerfile
    image: local/wordpress-fpm:latest
    container_name: wp_dev_wordpress
    restart: unless-stopped
    expose:
      - "9000" # php-fpm port (internal)
    volumes:
      - wordpress_data:/var/www/html
      - db_data:/var/lib/mysql
      - ./wp-content:/var/www/html/wp-content      
      - ./wp-config/wp-config.php:/var/www/html/wp-config.php
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DEBUG=1
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wp-network

  db:
    image: mariadb:10.6
    container_name: wp_dev_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./db/initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wp-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: wp_dev_phpmyadmin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PMA_HOST=db
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - wp-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: wp_dev_mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"
    networks:
      - wp-network

  wpcli:
    image: wordpress:cli
    container_name: wpcli
    entrypoint: [ "tail", "-f", "/dev/null" ]
    volumes:
      - ./wp-content:/var/www/html/wp-content
    env_file:
      - .env
    depends_on:
      - db
      - wordpress
    networks:
      - wp-network

volumes:
  db_data:
  wordpress_data:


networks:
  wp-network:
    driver: bridge
